#!/bin/bash

cpanm LWP::UserAgent.pm
cpanm Bio::AlignIO

# Install Erpin
wget -L http://rna.igmors.u-psud.fr/download/Erpin/erpin5.5.4.serv.tar.gz; tar xzvf erpin5.5.4.serv.tar.gz; cp erpin5.5.4.serv/bin/erpin /usr/local/bin/

# Install PirObject
git clone https://github.com/prioux/PirObject.git; cp PirObject/lib/PirObject.pm /etc/perl/;
# curl -o PirObject.tar.gz -L https://github.com/prioux/PirObject/archive/master.tar.gz;tar xzvf PirObject.tar.gz; cp PirObject-master/PirObject/lib/PirObject.pm /etc/perl/;

# Install all PirModels
git clone https://github.com/BFL-lab/PirModels.git; mv PirModels /root/

# Install flip
git clone https://github.com/BFL-lab/flip.git; cd flip/src/; gcc -o /usr/local/bin/flip flip.c;

# go back up in hierarchy after `cd`
cd ../..

# Install umac
git clone https://github.com/BFL-lab/umac.git; cp umac/umac /usr/local/bin/

# Install HMMsearchWC
git clone https://github.com/BFL-lab/HMMsearchWC.git; cp HMMsearchWC/HMMsearchCombiner /usr/local/bin/; cp HMMsearchWC/HMMsearchWrapper /usr/local/bin/

# Install RNAfinder
git clone https://github.com/BFL-lab/RNAfinder.git; cp RNAfinder/RNAfinder /usr/local/bin/; cp RNAfinder/DOT_RNAfinder.cfg ~/.RNAfinder.cfg

# Install mf2sqn
git clone https://github.com/BFL-lab/mf2sqn.git; cp mf2sqn/mf2sqn /usr/local/bin/; cp mf2sqn/qualifs.pl /usr/share/perl5/

# Install grab-fasta
git clone https://github.com/BFL-lab/grab-fasta.git; cp grab-fasta/grab-fasta /usr/local/bin/;cp grab-fasta/grab-seq /usr/local/bin/

# Install MFannot
git clone https://github.com/BFL-lab/mfannot.git; cp mfannot/mfannot /usr/local/bin/;cp -r mfannot/examples /

# Install data
git clone https://github.com/BFL-lab/MFannot_data.git

#Install BLAST matrix
#mkdir BLASTMAT; cd BLASTMAT; wget  ftp://ftp.ncbi.nlm.nih.gov/blast/matrices/* ; cd ..

#Copy RNAfinder config file
cp ~/.RNAfinder.cfg /

#mv PirModels 
mv /root/PirModels / 



####################
# Set ENV variable #
####################

export RNAFINDER_CFG_PATH=/
export MF2SQN_LIB=/mf2sqn/lib/
export MFANNOT_LIB_PATH=/MFannot_data/protein_collections/
export MFANNOT_EXT_CFG_PATH=/MFannot_data/config
export MFANNOT_MOD_PATH=/MFannot_data/models/
export BLASTMAT =/BLASTMAT/
export EGC=/MFannot_data/EGC/
export ERPIN_MOD_PATH=/MFannot_data/models/Erpin_models/
export PIR_DATAMODEL_PATH=/PirModels